apiVersion: v1
kind: PersistentVolume

metadata:
  name: local-nfs
  labels:
    content: models

spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /export/models
    server: 192.168.0.210

